### ISSUE TITLE
AzureStorage 1.8.7: lease lost and never re-acquired. No orchestrations processed.

### ISSUE THREAD

**Issue by jviau** [Azure/durabletask#575]
Yesterday I upgraded our DTFx packages:

DurableTask.Core: 2.5.2 -> 2.5.5
DurableTask.AzureStorage: 1.8.5 -> 1.8.7

What happened shortly after that was all of our workers logged this warning (of course the ids and times are slightly different between workers): 

```
mljobs-appplease: AppLeaseManager failed to renew lease. AppLeaseId: d98c1dd4-008f-04b2-e980-0998ecf8427e Exception: Microsoft.WindowsAzure.Storage.StorageException: The lease ID specified did not match the lease ID for the container.
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
    at DurableTask.AzureStorage.Partitioning.AppLeaseManager.RenewLeaseAsync() in C:\source\durabletask\src\DurableTask.AzureStorage\Partitioning\AppLeaseManager.cs:line 489
 Request Information
 RequestID:18f550f7-d01e-0017-1c49-784516000000
 RequestDate:Wed, 14 Jul 2021 00:44:29 GMT
 StatusMessage:The lease ID specified did not match the lease ID for the container.
 ErrorCode:LeaseIdMismatchWithLeaseOperation
 ErrorMessage:The lease ID specified did not match the lease ID for the container.
 RequestId:18f550f7-d01e-0017-1c49-784516000000
 Time:2021-07-14T00:44:29.4048692Z
```

After this warning, no lease was ever re-acquired and all of our workers effectively stopped processing **any** orchestrations until another deployment came along and restarted all the workers.

I see that 1.8.7 includes this change https://github.com/Azure/durabletask/pull/529. Is it related?

**Comment by cgillum** [comment]
Pinging @amdeel for this one.

**Comment by amdeel** [comment]
Hey @jviau. Could you provide me some more information so I can investigate this further? First, what is your AppName and region? Are there any other Apps sharing the same TaskHub on your storage account?

**Comment by jviau** [comment]
No other apps on the same storage account. This actually affected 2 separate task hubs that are completely independent of one another. One is in eastus2, the other is in westus2. The app name is "mljobs".

The fact that it impacted 2 completely independent task hubs (separate storage accounts, separate workers). Makes me think this might be a bug that only occurs when upgrading to a version with the change I linked?

**Comment by ConnorMcMahon** [comment]
This is not an app lease problem. This is a regression (#554) introduced in v2.5.5 of DurableTask.Core (which DurableTask.AzureStorage takes as a dependency), that causes a null reference bug to be thrown during orchestration completion on Release builds. This causes us to exit out of control queue dequeue loop for the partition. This means after a worker has completed a single orchestration, it will not poll any more messages from that partition until an application restart (yikes!).

The good news is that I fixed this bug in #560. The bad news is that I forgot to publish a corresponding version of DurableTask.Core when I published the hotfix release of v1.8.8 for DurableTask.AzureStorage, so that version still has this bug.

I will publish a version v2.5.6 of DurableTask.Core today with the fix, and at the same time I will publish v1.8.9 of DurableTask.AzureStorage that upgrades that dependency since it is broken with the current dependency on v2.5.5.

**Comment by jviau** [comment]
Thank you for the update @ConnorMcMahon !

Yes, I had a discussion offline with @amdeel , and the current thought is this is only an issue when you initially perform the upgrade, where there is a short period of time with both old and new versions running (for us, k8s is swapping out the old pods with new ones). So it _should_ only be a one time issue - and a simple restart fixes it. Hopefully, I can find some time to verify this.

**Comment by saguiitay** [comment]
Any chance that this still happens in 2.5.6 and 1.8.9?
(I don't have the traces available, but I suspect I'm facing a similar issue - workers stopped polling for messages until the process was restarted)

**Comment by amdeel** [comment]
@saguiitay For this incident it appeared that the reason this occurred was because the upgrade was specifically from 1.8.5 (or earlier) where multiple workers had different versions of code running at the same time during the upgrade. Did you also see this app lease renew error when processing stopped? Or do you relate instead to the null reference bug referenced above from Connor?

**Comment by saguiitay** [comment]
@amdeel probably related to the issue discussed by Connor. I'll open a separate issue to track this.

**Comment by jviau** [comment]
To update this, this reproduced in my test. The reproduction is fairly easy:

1. Have an k8s cluster running an app with DTFx.AzureStorage <= 1.8.5
2. Push a new deployment to the k8s cluster which upgrades to DTFx.AzureStorage > 1.8.5.

Since k8s will cycle the new pod in, while the old pod is still running, this will reproduce and the new pod will have that error in the original issue in its logs, and never re-acquire the lease.

**Comment by jviau** [comment]
Going to close as this is an old issue.
